//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityServer3.Core.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Events {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Events() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityServer3.Core.Resources.Events", typeof(Events).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Permissions Revoked.
        /// </summary>
        public static string ClientPermissionsRevoked {
            get {
                return ResourceManager.GetString("ClientPermissionsRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Security Policy (CSP) Report.
        /// </summary>
        public static string CspReport {
            get {
                return ResourceManager.GetString("CspReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login Error.
        /// </summary>
        public static string ExternalLoginError {
            get {
                return ResourceManager.GetString("ExternalLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login Failure.
        /// </summary>
        public static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Login Success.
        /// </summary>
        public static string ExternalLoginSuccess {
            get {
                return ResourceManager.GetString("ExternalLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Login Failure.
        /// </summary>
        public static string LocalLoginFailure {
            get {
                return ResourceManager.GetString("LocalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Login Success.
        /// </summary>
        public static string LocalLoginSuccess {
            get {
                return ResourceManager.GetString("LocalLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Event.
        /// </summary>
        public static string LogoutEvent {
            get {
                return ResourceManager.GetString("LogoutEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Login.
        /// </summary>
        public static string PartialLogin {
            get {
                return ResourceManager.GetString("PartialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Login Complete.
        /// </summary>
        public static string PartialLoginComplete {
            get {
                return ResourceManager.GetString("PartialLoginComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Login Failure.
        /// </summary>
        public static string PreLoginFailure {
            get {
                return ResourceManager.GetString("PreLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Login Success.
        /// </summary>
        public static string PreLoginSuccess {
            get {
                return ResourceManager.GetString("PreLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Owner Password Flow Login Failure.
        /// </summary>
        public static string ResourceOwnerFlowLoginFailure {
            get {
                return ResourceManager.GetString("ResourceOwnerFlowLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Owner Password Flow Login Success.
        /// </summary>
        public static string ResourceOwnerFlowLoginSuccess {
            get {
                return ResourceManager.GetString("ResourceOwnerFlowLoginSuccess", resourceCulture);
            }
        }
    }
}
